// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVNzl82U9o0RW7OT1u7eV8e_2haGpH_Rc',
    appId: '1:68933481586:web:6c8cca96d138d62c78feeb',
    messagingSenderId: '68933481586',
    projectId: 'allenvm-222600',
    authDomain: 'allenvm-222600.firebaseapp.com',
    storageBucket: 'allenvm-222600.appspot.com',
    measurementId: 'G-P91XR79VQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC07NxFnzxh9hi8QR2Z4-dpBvyTuKR7YN4',
    appId: '1:68933481586:android:83318280a535a7ff78feeb',
    messagingSenderId: '68933481586',
    projectId: 'allenvm-222600',
    storageBucket: 'allenvm-222600.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlBfyaLbrdrnfHvVu_VgcxuIb9bKbcMgw',
    appId: '1:68933481586:ios:4cbed2490ffa6db678feeb',
    messagingSenderId: '68933481586',
    projectId: 'allenvm-222600',
    storageBucket: 'allenvm-222600.appspot.com',
    iosClientId: '68933481586-r71s91oc07o86l24k3mfibsi8o8blkqo.apps.googleusercontent.com',
    iosBundleId: 'ca.mcmaster.audioapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlBfyaLbrdrnfHvVu_VgcxuIb9bKbcMgw',
    appId: '1:68933481586:ios:4cbed2490ffa6db678feeb',
    messagingSenderId: '68933481586',
    projectId: 'allenvm-222600',
    storageBucket: 'allenvm-222600.appspot.com',
    iosClientId: '68933481586-r71s91oc07o86l24k3mfibsi8o8blkqo.apps.googleusercontent.com',
    iosBundleId: 'ca.mcmaster.audioapp',
  );
}
